import LogementCheckbox from "../components/immeuble/ImmeubleTypeCheckbox"
import Search from "../components/inputs/Search"
import ImmeubleList from "../components/immeuble/ImmeubleList"
//import { useState, useEffect } from "react"
//import { getImmeubles } from "../utils/api/immeuble"

const Home: React.FC = () => {

  //const [immeubles, setImmeubles] = useState([])

  //useEffect(() => {
  //  getImmeubles().then((immeubles) => {
  //    setImmeubles(immeubles);
  //  })
  //})

  const immeubles = [
    {
      iid: 1,
      nom: "Lamiaceae",
      address: "42 Sunnyside Park",
      secteur: "Watuagung",
      type: "Condo/Loft",
      photos: "https://images.pexels.com/photos/439391/pexels-photo-439391.jpeg",
      descriptif: "Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
      price: 400,
      nombre_logements: 13,
      hot_water: true,
      electricity: true,
      wifi: true,
      parking: true,
      pool: true,
      gym: true,
      backyard: true,
      elevator: true,
      ev_charger: true,
      air_conditioner: true,
      terrasse: true
  },
  {
      iid: 2,
      nom: "Parmeliaceae",
      address: "14 Towne Parkway",
      secteur: "Heidelberg",
      type: "Appartements",
      photos: "https://www.lbkapts.com/uploads/images/BLOC-Apartments_8006.jpg",
      descriptif: "Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
      price: 500,
      nombre_logements: 7,
      hot_water: true,
      electricity: true,
      wifi: true,
      parking: true,
      pool: true,
      gym: true,
      backyard: true,
      elevator: true,
      ev_charger: true,
      air_conditioner: true,
      terrasse: true
  },
  {
      iid: 3,
      nom: "Dryopteridaceae",
      address: "72736 Village Drive",
      secteur: "Kebon",
      type: "Commercial",
      photos: "https://soumissionsentreprises.ca/wp-content/uploads/2021/11/assurance-pour-immeubles-commerciaux-quebec.jpeg",
      descriptif: "Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
      price: 600,
      nombre_logements: 3,
      hot_water: true,
      electricity: true,
      wifi: true,
      parking: true,
      pool: true,
      gym: true,
      backyard: true,
      elevator: true,
      ev_charger: true,
      air_conditioner: true,
      terrasse: true
  },
  {
      iid: 4,
      nom: "Lamiaceae",
      address: "42 Sunnyside Park",
      secteur: "Watuagung",
      type: "Condo/Loft",
      photos: "https://images.pexels.com/photos/439391/pexels-photo-439391.jpeg",
      descriptif: "Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
      price: 400,
      nombre_logements: 13,
      hot_water: true,
      electricity: true,
      wifi: true,
      parking: true,
      pool: true,
      gym: true,
      backyard: true,
      elevator: true,
      ev_charger: true,
      air_conditioner: true,
      terrasse: true
  },
  {
      iid: 5,
      nom: "Parmeliaceae",
      address: "14 Towne Parkway",
      secteur: "Heidelberg",
      type: "Appartements",
      photos: "https://www.lbkapts.com/uploads/images/BLOC-Apartments_8006.jpg",
      descriptif: "Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
      price: 500,
      nombre_logements: 7,
      hot_water: true,
      electricity: true,
      wifi: true,
      parking: true,
      pool: true,
      gym: true,
      backyard: true,
      elevator: true,
      ev_charger: true,
      air_conditioner: true,
      terrasse: true
  },
  {
      iid: 6,
      nom: "Dryopteridaceae",
      address: "72736 Village Drive",
      secteur: "Kebon",
      type: "Commercial",
      photos: "https://soumissionsentreprises.ca/wp-content/uploads/2021/11/assurance-pour-immeubles-commerciaux-quebec.jpeg",
      descriptif: "Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
      price: 600,
      nombre_logements: 3,
      hot_water: true,
      electricity: true,
      wifi: true,
      parking: true,
      pool: true,
      gym: true,
      backyard: true,
      elevator: true,
      ev_charger: true,
      air_conditioner: true,
      terrasse: true
  },
  {
      iid: 7,
      nom: "Lamiaceae",
      address: "42 Sunnyside Park",
      secteur: "Watuagung",
      type: "Condo/Loft",
      photos: "https://images.pexels.com/photos/439391/pexels-photo-439391.jpeg",
      descriptif: "Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
      price: 400,
      nombre_logements: 13,
      hot_water: true,
      electricity: true,
      wifi: true,
      parking: true,
      pool: true,
      gym: true,
      backyard: true,
      elevator: true,
      ev_charger: true,
      air_conditioner: true,
      terrasse: true
  },
  {
      iid: 8,
      nom: "Parmeliaceae",
      address: "14 Towne Parkway",
      secteur: "Heidelberg",
      type: "Appartements",
      photos: "https://www.lbkapts.com/uploads/images/BLOC-Apartments_8006.jpg",
      descriptif: "Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
      price: 500,
      nombre_logements: 7,
      hot_water: true,
      electricity: true,
      wifi: true,
      parking: true,
      pool: true,
      gym: true,
      backyard: true,
      elevator: true,
      ev_charger: true,
      air_conditioner: true,
      terrasse: true
  },
  {
      iid: 9,
      nom: "Dryopteridaceae",
      address: "72736 Village Drive",
      secteur: "Kebon",
      type: "Commercial",
      photos: "https://soumissionsentreprises.ca/wp-content/uploads/2021/11/assurance-pour-immeubles-commerciaux-quebec.jpeg",
      descriptif: "Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
      price: 600,
      nombre_logements: 3,
      hot_water: true,
      electricity: true,
      wifi: true,
      parking: true,
      pool: true,
      gym: true,
      backyard: true,
      elevator: true,
      ev_charger: true,
      air_conditioner: true,
      terrasse: true
  },
  {
      iid: 10,
      nom: "Lamiaceae",
      address: "42 Sunnyside Park",
      secteur: "Watuagung",
      type: "Condo/Loft",
      photos: "https://images.pexels.com/photos/439391/pexels-photo-439391.jpeg",
      descriptif: "Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
      price: 400,
      nombre_logements: 13,
      hot_water: true,
      electricity: true,
      wifi: true,
      parking: true,
      pool: true,
      gym: true,
      backyard: true,
      elevator: true,
      ev_charger: true,
      air_conditioner: true,
      terrasse: true
  },
  {
      iid: 11,
      nom: "Parmeliaceae",
      address: "14 Towne Parkway",
      secteur: "Heidelberg",
      type: "Appartements",
      photos: "https://www.lbkapts.com/uploads/images/BLOC-Apartments_8006.jpg",
      descriptif: "Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
      price: 500,
      nombre_logements: 7,
      hot_water: true,
      electricity: true,
      wifi: true,
      parking: true,
      pool: true,
      gym: true,
      backyard: true,
      elevator: true,
      ev_charger: true,
      air_conditioner: true,
      terrasse: true
  },
  {
      iid: 12,
      nom: "Dryopteridaceae",
      address: "72736 Village Drive",
      secteur: "Kebon",
      type: "Commercial",
      photos: "https://soumissionsentreprises.ca/wp-content/uploads/2021/11/assurance-pour-immeubles-commerciaux-quebec.jpeg",
      descriptif: "Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
      price: 600,
      nombre_logements: 3,
      hot_water: true,
      electricity: true,
      wifi: true,
      parking: true,
      pool: true,
      gym: true,
      backyard: true,
      elevator: true,
      ev_charger: true,
      air_conditioner: true,
      terrasse: true
  },
  {
      iid: 13,
      nom: "Lamiaceae",
      address: "42 Sunnyside Park",
      secteur: "Watuagung",
      type: "Condo/Loft",
      photos: "https://images.pexels.com/photos/439391/pexels-photo-439391.jpeg",
      descriptif: "Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
      price: 400,
      nombre_logements: 13,
      hot_water: true,
      electricity: true,
      wifi: true,
      parking: true,
      pool: true,
      gym: true,
      backyard: true,
      elevator: true,
      ev_charger: true,
      air_conditioner: true,
      terrasse: true
  },
  {
      iid: 14,
      nom: "Parmeliaceae",
      address: "14 Towne Parkway",
      secteur: "Heidelberg",
      type: "Appartements",
      photos: "https://www.lbkapts.com/uploads/images/BLOC-Apartments_8006.jpg",
      descriptif: "Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
      price: 500,
      nombre_logements: 7,
      hot_water: true,
      electricity: true,
      wifi: true,
      parking: true,
      pool: true,
      gym: true,
      backyard: true,
      elevator: true,
      ev_charger: true,
      air_conditioner: true,
      terrasse: true
  },
  {
      iid: 15,
      nom: "Dryopteridaceae",
      address: "72736 Village Drive",
      secteur: "Kebon",
      type: "Commercial",
      photos: "https://soumissionsentreprises.ca/wp-content/uploads/2021/11/assurance-pour-immeubles-commerciaux-quebec.jpeg",
      descriptif: "Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
      price: 600,
      nombre_logements: 3,
      hot_water: true,
      electricity: true,
      wifi: true,
      parking: true,
      pool: true,
      gym: true,
      backyard: true,
      elevator: true,
      ev_charger: true,
      air_conditioner: true,
      terrasse: true
    },   
  ]

    return (
      <div className="flex flex-col mx-3 md:px-10 lg:px-20">
        <section className="mt-2 md:mt-4">
          <Search id="immeuble-search" placeholder="Rechercher un immeuble..." />
          <LogementCheckbox />
        </section>
        <section className="mt-2 md:mt-4">
          <ImmeubleList immeubles={immeubles} />
        </section>
      </div>
    )
  }
  
  export default Home